### ISSUE TITLE
UB3R manual twitter feed setup?

### ISSUE THREAD

**Issue by RichGriese** [moiph/ub3r-b0t#1]
Hey moiph,

I saw a line in your https://ub3r-b0t.com/commands page that says... "Rss/twitter feeds to push to a channel of your choosing! Manual setup for now, contact moiph." I'm looking to push one twitter use into my servers channel, so that as they tweet the tweets get pushed into the Discord server. Is this what you can help me set up? Looking forward to hearing from you.

Cheers! Rich / @RichGriese on Twitter or on Discord you can find me via a link on http://webulite.com

**Comment by moiph** [comment]
Yep, that's the feature -- just haven't put time in self-service via the admin settings panel yet :)
I'd need the server's ID and channel ID to push the data to (you can type .debug to get them) and then the twitter username.

**Comment by RichGriese** [comment]
Pat, Thanks so much for contacting me. The .debug info is...

Server ID: 205459278365065218
Channel ID: 210575456334774274
and the twitter name is @webulite

Cheers!

**Comment by RichGriese** [comment]
Pat, UB3R just posted the lastest tweet from the Twitter @webulite user. Looks like you got in info & did the magic. the bot's output line is very clean. Now... I'm hoping as new tweets are made, the bot will post them within a reasonable amount of time. Thanks. you are the best. Cheers! Rich

**Comment by moiph** [comment]
Glad I could help!

**Comment by RichGriese** [comment]
Moiph, I'm sorry to be a pain in your ass, but would you mind changing the by hand set up you did for me to  to have the bot post in a different channel? The way my evolution occurred I was not using my default channel. I want to kill all but the default channel, and that means moving the bot.

The new .debug info is;

Server ID: 205459278365065218 | Channel ID: 205459278365065218 | Your ID: 204765209267535872

Sorry for the inconvenience. BTW... the bot posting has been perfect.

Cheers! Rich

**Comment by moiph** [comment]
No worries, getting rid of the manual steps is on my TODO list :)  Should be updated now.

**Comment by RichGriese** [comment]
You are the greatest!
