### ISSUE TITLE
Bot doesn't unescape titles/text

### ISSUE THREAD

**Issue by mayvid14** [moiph/ub3r-b0t#12]
Currently, the bot shows the titles without unescaping them, which is problematic for most of the people.

![Screenshot (50)_LI](https://user-images.githubusercontent.com/17515490/58888993-d6369b80-8705-11e9-8013-e0a2135d8a6f.jpg)

It should be **Kyoukai no Kanata Movie: I'll be here - Kako-hen - Yakusoku no Kizuna**

**Comment by moiph** [comment]
Thanks for reporting, this has been fixed
