### ISSUE TITLE
Google search command returns Feed Proxy link instead of true URL

### ISSUE THREAD

**Issue by ingochris** [moiph/ub3r-b0t#13]
```
> [18:46] ingochris: .g uber bot
> [18:46] UB3R-B0T: https://feedproxy.google.com/~r/venturebeat/SZYF/~3/h-2RwIq11ys/
```

Clicking through redirects (feedproxy/feedburner feature) to
> https://venturebeat.com/2017/01/07/bot-evangelist-chris-messina-leaves-uber/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+venturebeat%2FSZYF+%28VentureBeat%29

We have already tried a new Google API key in our bot instance.

Can anyone advise how to remedy this issue?

**Comment by moiph** [comment]
Please make sure you don't have any sites configured in the "Site to search section"

![image](https://user-images.githubusercontent.com/102394/60771391-6ddc3080-a09c-11e9-9552-1b27da600f49.png)
