### ISSUE TITLE
Timer command called by another bot

### ISSUE THREAD

**Issue by ALPIXELMaiki** [moiph/ub3r-b0t#14]
Hi,

I developed a bot with nodeJS, and i would like create some reminder with it.
When my bot send message 'hey buttmunch remind me....', so the bot does not create a reminder.

Dos a bot can create reminders ? Is there a way to do that with a bot, and not with a manual writing ? thanks !

**Comment by xinitrc-dev** [comment]
Hey! I'm a helper for the Ub3r's support server.
Ub3r will ignore any messages sent by other bots, so, unfortunately, it is not possible for your bot to trigger ub3r's reminder command.

**Comment by ALPIXELMaiki** [comment]
Thanks for your answer !
