### ISSUE TITLE
suggestion: games search with IGDB

### ISSUE THREAD

**Issue by ghost** [moiph/ub3r-b0t#15]
their API is unlimited for both open source and commercial use, URL embeds look like this with the new site:
![image](https://user-images.githubusercontent.com/7173984/69490718-34dd0680-0e59-11ea-80f8-ec76232ba1c3.png)
URL embeds for existing site:
![image](https://user-images.githubusercontent.com/7173984/69490739-7f5e8300-0e59-11ea-9bdf-d6b5d6dbebe1.png)

the search is pretty good for fuzzy matches.

**Is your feature request related to a problem? Please describe.**

Add a games search option to ub3r-b0t and use IGDB since their [API is free with no restrictions on data licensing](https://api.igdb.com/) compared to mobygames and the like. There are multiple ways to consume the api and there is already a [reference bot](https://gitlab.com/SirRandall/Bender) that does so.

**Describe the solution you'd like**

`s!igdb <search term>`  brings up a card with info on the search term.
**Describe alternatives you've considered**

Some bots offer a Steam search option, but it doesn't include console games or games only available by physical copy or through GOG/EGS/Itch/etc.

Currently the bot hosted in their server is only available there. I don't trust myself to self host the reference bot in a secure way.

**Additional context**
![image](https://user-images.githubusercontent.com/7173984/69056718-8e1ee300-09de-11ea-8f82-d7321232b86b.png)
![image](https://user-images.githubusercontent.com/7173984/69056893-e3f38b00-09de-11ea-988d-d26386cddd36.png)

**Comment by moiph** [comment]
Thanks for the suggestion -- this is live now :)
