### ISSUE TITLE
.title command seems to be not working

### ISSUE THREAD

**Issue by xinitrc-ls** [moiph/ub3r-b0t#2]
![untitled](https://cloud.githubusercontent.com/assets/14354528/21765440/e91236ce-d636-11e6-9c34-b95ee4311ccf.png)
After initial "send typing" no response has been recieved. ¯_(ツ)_/¯

**Comment by xinitrc-ls** [comment]
![untitled](https://cloud.githubusercontent.com/assets/14354528/21765423/cb1bc63a-d636-11e6-9df8-c0f1ec098d8c.png)
After initial "send typing" no response has been recieved. ¯\_(ツ)_/¯

**Comment by moiph** [comment]
Forgot this was still opened. Was fixed some time ago :)
