### ISSUE TITLE
suggestion: support libre.fm in .fm and .fmyt commands

### ISSUE THREAD

**Issue by ralsei** [moiph/ub3r-b0t#20]
maybe it's just a me thing, I don't know, but it's not like it's very difficult to implement -- the APIs are the same, and the Libre.fm API doesn't actually require API keys.

**Comment by moiph** [comment]
It actually was supported, I think something broke along the way and I forgot to fix it. I have unforgotten, will look into it :)

**Comment by moiph** [comment]
`.librefm` and `.librefmyt` should now be working again.
