### ISSUE TITLE
.role and .derole commands resulting in a typo.

### ISSUE THREAD

**Issue by Jamiecode** [moiph/ub3r-b0t#23]
When using the .role and .derole commands with the Discord bot, I end up getting the corresponding error messages.

.role gives "access granted to role Orange. congratulation !"

.derole gives "access removed from role Hyper Blue. congratulation ... ?"

I believe there should be a s and the end of "congratulation".  If this is intended behavior please ignore.

**Comment by moiph** [comment]
this one is by design
