### ISSUE TITLE
Weather Information Wrong for One Person in Server

### ISSUE THREAD

**Issue by LadieWinter** [moiph/ub3r-b0t#26]
There is one person in our server whose weather information has been consistently wrong for a little now. Week or two, if I remember correctly. Out of three or four other people, he is the only person this is happening to.
![weatherinformation](https://user-images.githubusercontent.com/39286142/121748988-e85b2980-cad7-11eb-863c-6fcc813773a6.png)

**Comment by moiph** [comment]
Followed up in chat, cached location data was bad; fixed.
