### ISSUE TITLE
Logging broken upon deleting log channel

### ISSUE THREAD

**Issue by TheRealWhoop** [moiph/ub3r-b0t#27]
We had a #mod-log channel which we recreated to clear the contents in preparation for onboarding new lesser permissioned moderators. Upon doing so as expected ub3r-bot errored reporting the channel is missing. However when you set to the new channel it still returns "Invalid update channel -- channel not found".

Attempts to set it to "(disabled)" to turn the logging functionality off and again result in the error "Invalid update channel -- channel not found" - it appears stuck in this state and we're unable to resolve.

**Comment by moiph** [comment]
I'll fix the error messaging, that error text got repurposed for a different option and I forgot to update it. The problem is you have admin panel audit logging enabled to a channel that no longer exists.

**Comment by TheRealWhoop** [comment]
It doesn't allow me to set to a channel that does exist though, it continues to return that error.

**Comment by moiph** [comment]
That should only happen in a small time window if it's a new channel for example. Can help debug if you stop by the support server

**Comment by TheRealWhoop** [comment]
I'm afraid it doesn't, I just retried over a week after, it still errors when trying to change the channel (or save anything at all). I'll swing by the support server.
