### ISSUE TITLE
imdb command: show rating

### ISSUE THREAD

**Issue by CryDeS** [moiph/ub3r-b0t#28]
Rn that command display movie title and link to imdb, will be cool if it shows also raiting

i.e
was:
Venom: Let There Be Carnage (2021) 

http://www.imdb.com/title/tt7097896/?ref_=fn_al_tt_1

want something like that:
Venom: Let There Be Carnage (2021) [6.0/10]

http://www.imdb.com/title/tt7097896/?ref_=fn_al_tt_1

**Comment by moiph** [comment]
Thanks for the bug report; fixed.

**Comment by CryDeS** [comment]
Broken again

For testing:
.imdb Venom 2
/imdb Venom 2
