### ISSUE TITLE
Tracking Incorrect Carrier

### ISSUE THREAD

**Issue by L3thal1ty** [moiph/ub3r-b0t#3]
Trying to track a USPS package, keeps returning with "Invalid tracking number (according to FedEx)"

**Comment by moiph** [comment]
If you don't mind joining the UB3R-B0T discord server we can debug it -- likely an issue with that particular tracking #, other USPS tracking is working so it's just a misdetection.

**Comment by L3thal1ty** [comment]
Not sure how to go about finding said discord channel. Is there a join link somewhere?

**Comment by L3thal1ty** [comment]
It tracks fine on USPS website directly, and my UPS package is tracking fine, not sure what to say.

**Comment by moiph** [comment]
it's on https://ub3r-b0t.com -- https://discord.gg/0t6waxpRf4xvyNHj

**Comment by moiph** [comment]
Fixed tracking detection.
