### ISSUE TITLE
.w returns either 0% or 100% for chance of precipitation

### ISSUE THREAD

**Issue by enamelizer** [moiph/ub3r-b0t#36]
Example output:
`Light rain, 42F (6C) (279K) / feels like 41F (5C) (278K) | High: 42F (6C) (279K) | Low: 41F (5C) (278K) | Humidity: 85% | Wind: WSW @ 3mph (5km/h) | 0% chance of precipitation (Seattle, WA 98126, USA)`

My guess is that the value from the API call is not getting converted to a percentage correctly.

This commit is possibly related:
https://github.com/moiph/OpenWeatherMap.API/commit/cfe66ceed73d9484d7749d298139018c05b5582a

**Comment by moiph** [comment]
Woops, I patched that part and didn't fix up the usage for the bot. Thanks for catching and reporting. Fixed now :)

**Comment by ahpook** [comment]
This is fixed upstream : https://github.com/thomasgalliker/OpenWeatherMap.API/blob/develop/OpenWeatherMap/Models/WeatherForecastItem.cs#L34

@moiph if you update your fork this will get fixed for free 👍
