### ISSUE TITLE
Suggestion: Random greeting message with integrated commands.

### ISSUE THREAD

**Issue by calif94577** [moiph/ub3r-b0t#37]
First off awesome bot!!! So much functionality!

Would be nice to be able to input several greeting messages and have it randomly choose one.

Also allowing for command inside the greeting like "Welcome %user% you rolled a .roll 20" and have the command work.

**Comment by moiph** [comment]
I opted not to do the integrated command suggestion but you can now add multiple greeting / farewell options and they will be chosen at random!
