### ISSUE TITLE
Formatting issue when announcing tweets from users with underscore

### ISSUE THREAD

**Issue by waggz81** [moiph/ub3r-b0t#6]
There seems to be an issue on twitter announcements when the user name has an underscore. For instance, 

[Tweet from Porphyro_] https://twitter.com/Porphyro_/status/882385616205369346

ends up being 

![image](https://user-images.githubusercontent.com/20745474/27844667-46d81c36-60ea-11e7-90e5-03da208d73dc.png)

This also is partially an issue with the .twitter command:
![image](https://user-images.githubusercontent.com/20745474/27844683-756d7d52-60ea-11e7-8bce-106290ee0c94.png)

The tweet is correct but link is incorrect.

**Comment by moiph** [comment]
I think this was fixed by some Discord client updates, testing locally I no longer repro the issue.  Let me know if you see otherwise.
